import Head from "next/head";
import Image from "next/image";
import Title from "../components/Title";
import DisplayBasicInfo from "../components/BasicInfo";
import DisplayEventInfo from "../components/Events/EventInfo";
import NewPlayerPage from "../components/NewPlayerPage";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import data from "../BasicData.json";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Title data={data.main} />
        <DisplayBasicInfo data={data.main} />
        <DisplayEventInfo />
        <NewPlayerPage data={data.main} />
      </main>
    </>
  );
}
