import Head from "next/head";
import Image from "next/image";
import DisplayBasicInfo from "../components/BasicInfo";
import DisplayEventInfo from "../components/Events/EventInfo";
import NewPlayerPage from "../components/NewPlayerPage";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import data from "../BasicData.json";
const inter = Inter({ subsets: ["latin"] });

import clientPromise from "../lib/mongodb";

export async function getServerSideProps() {
  try {
    // `await clientPromise` will use the default database passed in the MONGODB_URI
    // get database
    const client = await clientPromise;
    const db = client.db("softball").collection("events");

    // Execute queries against database
    const response = await db.find({}, { _id: 0, name: 1, email: 1 }).toArray();
    const result = JSON.parse(JSON.stringify(response));

    return {
      props: { result },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { error: "db-events-could-not-find" },
    };
  }
}

export default function Home(props) {
  const eventData = props.result;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DisplayBasicInfo data={data.main} />
      <DisplayEventInfo result={eventData} />
      <NewPlayerPage data={data.main} />
    </>
  );
}
